name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
      
       steps:
       - uses: webfactory/ssh-agent@v0.5.1
         with: 
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       - name: Git Sync
         run: |
            git clone https://github.com/KuzRomanDocker/Task3.git
            git clone https://github.com/KuzRomanDocker/TEST.git
            rsync -avr --exclude='.git' --exclude='.github' --delete Task3/. TEST
            cd TEST
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git add .
            git commit -m "git log -1 --format=%B"
            git push --mirror git@github.com:KuzRomanDocker/TEST.git
